Add minio, paper and proxy deployments
kryonitelabs/kryocloud-test-infrastructure pull request #1
Opened 2021-09-18 07:40 UTC by ItsKev

## Proposed Changes

- Add minio

2021-09-30 20:08 UTC, lusu007 requested changes

2021-09-30 20:08 UTC, lusu007 commented on paper/Dockerfile
> +COPY eula.txt /app/eula.txt
When we use the startup parameter `-Dcom.mojang.eula.agree=true` instead of copying the eula.txt we could remove this copy layer.

2021-10-02 18:22 UTC, ItsKev commented on paper/Dockerfile
> +COPY eula.txt /app/eula.txt
Fixed

2021-10-02 18:34 UTC, lusu007 approved these changes

2021-10-02 18:34 UTC, merged